title       : "DS-Homebrew Wiki"
description : "Wikis for DS-Homebrew projects"
repo        : "DS-Homebrew/wiki"
color       : "#072f4f"
image       : "https://avatars1.githubusercontent.com/u/46971470?s=200&v=4"

exclude: [nitrofiles, node_modules, screenshot.png, palette.png]

collections_dir: pages

defaults:
  - scope:
      path: ""
    values:
      layout: "manual-page"

collections:
  en:
    output: true
  ic:
    output: true
  da:
    output: true
  de:
    output: true
  es:
    output: true
  fr:
    output: true
  he:
    output: true
  hu:
    output: true
  id:
    output: true
  it:
    output: true
  ja:
    output: true
  ko:
    output: true
  nl:
    output: true
  "no":
    output: true
  pl:
    output: true
  pt:
    output: true
  ru:
    output: true
  sv:
    output: true
  tr:
    output: true
  uk:
    output: true
  zh-CN:
    output: true
  zh-TW:
    output: true
