title       : "DS-Homebrew Wiki"
description : "Wikis for DS-Homebrew projects"
repo        : "DS-Homebrew/wiki"
color       : "#072f4f"
image       : "https://avatars1.githubusercontent.com/u/46971470?s=200&v=4"

exclude: [nitrofiles, node_modules, screenshot.png, palette.png]

collections_dir: pages

collections:
  english:
    output: true
  In-Context:
    output: true
  danish:
    output: true
  dutch:
    output: true
  german:
    output: true
  spanish:
    output: true
  french:
    output: true
  hebrew:
    output: true
  hungarian:
    output: true
  indonesian:
    output: true
  italian:
    output: true
  japanese:
    output: true
  korean:
    output: true
  norwegian:
    output: true
  polish:
    output: true
  portuguese:
    output: true
  russian:
    output: true
  swedish:
    output: true
  turkish:
    output: true
  ukrainian:
    output: true
  chinese_s:
    output: true
  chinese_t:
    output: true
