"project_id_env": "TWILIGHT_CROWDIN_ID"
"api_token_env": "CROWDIN_TOKEN"
preserve_hierarchy: true

files:
  - source: /pages/_en/*.md
    translation: /pages/_%two_letters_code%/%original_file_name%
  - source: /_data/en/*.json
    translation: /_data/%two_letters_code%/%original_file_name%