"project_id_env": "TWILIGHT_CROWDIN_ID"
"api_token_env": "CROWDIN_TOKEN"
preserve_hierarchy: true

files:
  - source: /pages/_english/*.md
    translation: /pages/_%language%/%original_file_name%
  - source: /_data/english/*.json
    translation: /_data/%language%/%original_file_name%