name: Upload source files to Crowdin

on:
  push:
    branches: [ main ]
    paths:
      - 'pages/en/**.md'
      - '_data/_en/**.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.2.11

      - name: Install Dependencies
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Test build
        run: deno run --unstable --allow-env --allow-run --allow-net --allow-read --allow-write deno.ts web

      - name: Push to Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
