name: Build pages for TWiLight Menu++

on:
  push:
    branches: ["*"]
    paths-exclude: [README.md, crowdin.yml]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg jq nodejs npm p7zip-full -y

          # sudo gem install bundler jekyll
          # bundle install

          npm install
      - name: Build manual pages
        run: ./convert.js
      - name: Pack 7z Package for nightly
        run: |
          cd nitrofiles
          7z a ../pages.7z pages
      - name: Upload to pages release
        run: |
          ID=35207926
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"

          # Update description
          UPLOAD_URL="https://api.github.com/repos/${{ github.repository }}/releases/$ID"
          curl -XPATCH -H "$AUTH_HEADER" "$UPLOAD_URL" -d "{\"body\": \"This release always has the latest page files\n\nLast updated: $(git rev-parse --short HEAD)\"}"

          # Delete old file
          ASSET_ID=$(curl https://api.github.com/repos/${{ github.repository }}/releases/$ID/assets | jq --raw-output '.[0].id')
          UPLOAD_URL="https://api.github.com/repos/${{ github.repository }}/releases/assets/$ASSET_ID"
          curl -XDELETE -H "$AUTH_HEADER" "$UPLOAD_URL"

          # Upload new file
          CONTENT_LENGTH="Content-Length: $(stat -c%s pages.7z)"
          CONTENT_TYPE="Content-Type: application/7z-x-compressed"
          UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/$ID/assets?name=pages.7z"
          curl -XPOST -H "$AUTH_HEADER" -H "$CONTENT_LENGTH" -H "$CONTENT_TYPE" --upload-file pages.7z "$UPLOAD_URL"
