name: Build pages for TWiLight Menu++

on:
  push:
    branches: ["*"]
    paths:
      - "pages/*"
      - "nitrofiles/*"
      - ".github/workflows/pages.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get install chromium-browser ffmpeg fonts-noto-cjk libxml2-utils p7zip-full python3 -y
      - name: ffmpeg -version
        run: ffmpeg -version
      - name: Build manual pages
        run: make -C pages
      - name: Pack 7z Package for nightly
        run: |
          cd nitrofiles
          7z a ../pages.7z pages
      - name: Upload to pages release
        run: |
          ID=35207926
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"

          curl -XPATCH -H "$AUTH_HEADER" "$UPLOAD_URL" -d "{\"body\": \"This release always has the latest page files\n\nLast updated: $(git rev-parse --short HEAD)\"}"

          for file in pages.7z; do
            CONTENT_LENGTH="Content-Length: $(stat -c%s $file)"
            CONTENT_TYPE="Content-Type: application/7z-x-compressed"
            UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/$ID/assets?name=$(basename $file)"

            curl -XPOST -H "$AUTH_HEADER" -H "$CONTENT_LENGTH" -H "$CONTENT_TYPE" --upload-file "$file" "$UPLOAD_URL"
          done
